# Generated by Django 4.0.6 on 2023-03-04 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DepotApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nom2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point_Depart', models.CharField(max_length=50)),
                ('Point_darrivée', models.CharField(max_length=50)),
                ('prix_Transport', models.IntegerField(default=0)),
                ('date_depart', models.DateField()),
                ('prix_de_facture', models.FloatField()),
                ('clarque', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('quantity_Init', models.IntegerField()),
                ('quantity_Act', models.IntegerField(default=0)),
                ('quantity_Vend', models.IntegerField(default=0)),
                ('prix_u_TTC', models.FloatField()),
                ('prix_vente_TTC', models.FloatField(default=0)),
                ('total_achat', models.FloatField(default=0)),
                ('total_vendu', models.FloatField(default=0)),
                ('benefice', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepotApp.category')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepotApp.depot')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_Vendu', models.IntegerField()),
                ('total_vente', models.FloatField(default=0)),
                ('vendu_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DepotApp.produit')),
            ],
        ),
    ]
