# Generated by Django 4.0.6 on 2023-03-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepotApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='clarque',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='date_depart',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='prix_de_facture',
        ),
    ]
