# Generated by Django 4.0.6 on 2023-03-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepotApp', '0004_operation_clarque_operation_date_depart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='clarque',
        ),
    ]
