# Generated by Django 4.0.6 on 2023-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotApp', '0005_remove_operation_clarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='clarque',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
