# Generated by Django 4.0.6 on 2023-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotApp', '0006_operation_clarque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nom2',
        ),
        migrations.AlterField(
            model_name='operation',
            name='clarque',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
