# Generated by Django 4.0.6 on 2023-03-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotApp', '0007_remove_category_nom2_alter_operation_clarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
