# Generated by Django 4.0.6 on 2023-03-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotApp', '0009_operation_pallete_alter_operation_clarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='Total',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
    ]
